import { Marcellus } from "next/font/google"
import "./globals.css"

const marcellus = Marcellus({
  subsets: ["latin", "latin-ext"],
  weight: "400",
})

// const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "K M Choksi",
  description: "Generated by create next app",
  icons: [
    {
      url: "/favicon.png",
      href: "/favicon.png",
    },
  ],
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={marcellus.className}>{children}</body>
    </html>
  )
}
